package me.jackcw.duels.message;

import me.jackcw.jcore.message.MessageKey;

public enum Message implements MessageKey
{
    ADMIN_HELP("admin.help"),
    NO_ARENAS("admin.no-arenas"),
    DUEL_HELP("duel.help"),
    CHALLENGE_CANNOT_SELF("duel.cannot-challenge-self"),
    CHALLENGE_ALREADY_PENDING("duel.already-pending"),
    CHALLENGE_SENT("duel.challenge-sent"),
    CHALLENGE_RECEIVED("duel.challenge-received"),
    CHALLENGE_NO_PENDING("duel.no-pending"),
    CHALLENGE_ACCEPTED("duel.accepted"),
    CHALLENGE_ACCEPTED_OPPONENT("duel.accepted-opponent"),
    CHALLENGE_DECLINED("duel.declined"),
    CHALLENGE_DECLINED_OPPONENT("duel.declined-opponent"),
    CHALLENGE_CANCELLED_DISCONNECT("duel.cancelled-disconnect"),
    CHALLENGE_EXPIRED("duel.challenge-expired"),
    NO_ARENA_AVAILABLE("duel.no-arena-available"),
    PREPARING_ARENA("duel.preparing-arena"),
    ALREADY_IN_MATCH("duel.already-in-match"),
    TARGET_IN_MATCH("duel.target-in-match"),
    MATCH_START("duel.match-start"),
    OUT_OF_BOUNDS_WARNING("duel.out-of-bounds-warning"),
    OUT_OF_BOUNDS_RETURNED("duel.out-of-bounds-returned"),
    SPECTATE_STARTED("duel.spectate-started"),
    SPECTATE_STOPPED("duel.spectate-stopped"),
    SPECTATE_RESTORED("duel.spectate-restored"),
    SPECTATE_MATCH_ENDED("duel.spectate-match-ended"),
    SPECTATE_NOT_SPECTATING("duel.spectate-not-spectating"),
    SPECTATE_ALREADY("duel.spectate-already"),
    SPECTATE_CANNOT_SELF("duel.spectate-cannot-self"),
    SPECTATE_WHILE_IN_MATCH("duel.spectate-while-in-match"),
    SPECTATE_TARGET_NOT_IN_MATCH("duel.spectate-target-not-in-match"),
    SPECTATE_MATCH_UNAVAILABLE("duel.spectate-match-unavailable"),
    SPECTATE_ARENA_NO_BOUNDS("duel.spectate-arena-no-bounds"),
    SPECTATE_TELEPORT_FAILED("duel.spectate-teleport-failed"),
    SPECTATE_NO_MATCHES("duel.spectate-no-matches"),
    MATCH_WIN("duel.match-win"),
    MATCH_LOSE("duel.match-lose"),
    ARENA_CREATED("admin.arena-created"),
    ARENA_DELETED("admin.arena-deleted"),
    ARENA_NOT_FOUND("admin.arena-not-found"),
    ARENA_SPAWN_SET("admin.arena-spawn-set"),
    ARENA_SPAWN_NOT_SET("admin.arena-spawn-not-set"),
    ARENA_INVALID_SPAWN("admin.arena-invalid-spawn"),
    ARENA_RENAMED("admin.arena-renamed"),
    ARENA_LIST_ENTRY("admin.arena-list-entry"),
    ARENA_ENABLED("admin.arena-enabled"),
    ARENA_DISABLED("admin.arena-disabled"),
    ARENA_IN_USE("admin.arena-in-use"),
    ARENA_BOUNDS_SET("admin.arena-bounds-set"),
    ARENA_BOUNDS_NOT_SET("admin.arena-bounds-not-set"),
    ARENA_BOUNDARY_SET("admin.arena-boundary-set"),
    ARENA_KIT_TOGGLED("admin.arena-kit-toggled"),
    ARENA_INVALID_BOUNDS_CORNER("admin.arena-invalid-bounds-corner"),
    ARENA_EDIT_MODE_EXITED("admin.arena-edit-mode-exited"),
    ARENA_STRUCTURE_CORNER_SET("admin.arena-structure-corner-set"),
    ARENA_STRUCTURE_CORNER_NOT_SET("admin.arena-structure-corner-not-set"),
    ARENA_TEMPLATE_CAPTURED("admin.arena-template-captured"),
    ARENA_TEMPLATE_CAPTURE_FAILED("admin.arena-template-capture-failed"),
    ARENA_TEMPLATE_INFO("admin.arena-template-info"),
    ARENA_TEMPLATE_CLEARED("admin.arena-template-cleared"),
    ARENA_PROVISIONING_SET("admin.arena-provisioning-set"),
    ARENA_INSTANCE_CREATED("admin.arena-instance-created"),
    ARENA_INSTANCE_DELETED("admin.arena-instance-deleted"),
    ARENA_INSTANCE_NOT_FOUND("admin.arena-instance-not-found"),
    ARENA_INSTANCE_IN_USE("admin.arena-instance-in-use"),
    ARENA_INSTANCE_LIST_ENTRY("admin.arena-instance-list-entry"),
    CANNOT_OPEN_INVENTORY_WHILE_IN_EDIT_MODE("admin.cannot-open-inventory-while-in-edit-mode"),
    KIT_CREATED("admin.kit-created"),
    KIT_DELETED("admin.kit-deleted"),
    KIT_NOT_FOUND("admin.kit-not-found"),
    KIT_RENAMED("admin.kit-renamed"),
    KIT_SAVED("admin.kit-saved"),
    KIT_ICON_SET("admin.kit-icon-set"),
    KIT_ICON_EMPTY_HAND("admin.kit-icon-empty-hand"),
    NO_KITS("admin.no-kits"),
    KIT_SELECTED("duel.kit-selected"),
    NOT_IN_DUEL("duel.not-in-duel"),
    KIT_SELECTION_CLOSED("duel.kit-selection-closed"),
    STATS_LOAD_FAILED("duel.stats-load-failed"),
    PLAYER_RECORD("duel.player-record"),
    NO_KITS_ALLOWED("duel.no-kits-allowed"),
    KIT_LIST_ENTRY("admin.kit-list-entry"),
    MENU_INVALID_NAME("menu.invalid-name"),
    MENU_INVALID_NUMBER("menu.invalid-number"),
    ARENA_BOUNDARY_GRACE_PROMPT("menu.arena-boundary-grace-prompt"),
    ARENA_RENAME_PROMPT("menu.arena-rename-prompt"),
    ARENA_CREATE_PROMPT("menu.arena-create-prompt"),
    KIT_RENAME_PROMPT("menu.kit-rename-prompt"),
    KIT_CREATE_PROMPT("menu.kit-create-prompt"),
    MENU_INPUT_CANCELLED("menu.input-cancelled"),
    STATE_RESTORED("player.state-restored");

    private final String path;

    Message(String path)
    {
        this.path = path;
    }

    @Override
    public String getPath()
    {
        return path;
    }
}
